### ISSUE TITLE
getting TypeError after running it one time

### ISSUE THREAD

**Issue by codeanticode** [mmilidoni/github-downloads-count#15]
After installing the latest release (1.2 beta), I can get download counts the first few times I run the gdc command, but shortly afterwards I start getting the following error:

```
Traceback (most recent call last):
  File "./gdc", line 48, in <module>
    full_names.insert(0, ensure_str(rep['full_name']))
TypeError: string indices must be integers
```

I'm on Mac OS X 10.10.5

**Comment by nathan-osman** [comment]
I'm seeing this too:

    nathan@nathan-desktop:~$ gdc nitroshare
    Traceback (most recent call last):
      File "gdc", line 48, in <module>
        full_names.insert(0, ensure_str(rep['full_name']))
    TypeError: string indices must be integers

I'm running the script in Python 2.7.9 on Ubuntu 15.04.

**Comment by anselal** [comment]
Cannot replicate the issue. I think this issue is resolved.

**Comment by anselal** [comment]
Me too. After running a few times `./gdc anselal` i get:

```
Traceback (most recent call last):
  File "./gdc", line 53, in <module>
    full_names.insert(0, ensure_str(rep['full_name']))
TypeError: string indices must be integers
```

**Comment by fabiovix** [comment]
I'm getting this error  too..."TypeError: string indices must be integers"
